- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleGhostRoleHunter
  name: Fugitive Hunter Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-hunter
    exclusiveAntag: false
    antagPrototype: Traitor
  - type: HunterRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleGhostRoleFugitive
  name: Fugitive Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    subtype: role-subtype-fugitive
    exclusiveAntag: false
    antagPrototype: Traitor
  - type: FugitiveRole
