# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleMorph
  name: Morph Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-morph
    exclusiveAntag: true
    antagPrototype: Morph
