- type: antag
  id: Xenomorph
  name: roles-antag-xenomorph-name
  antagonist: true
  objective: roles-antag-xenomorph-objective
  creditImage: /Textures/_Trauma/EndCredits/Antags/xenos.png

- type: antagSpecifier
  id: Xenomorph
  prefRoles: [ XenomorphsInfestationRoundstart ]
  spawnerPrototype: SpawnPointGhostXenomorph
  briefing:
    text: xenomorph-role-greeting
    color: "#8c3986"
