# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  abstract: true
  parent: OrganBaseInternal
  id: BaseAugment
  components:
  - type: Augment
  - type: SurgeryTool
    ignoreToggle: true # ItemToggle is used for augment logic not surgical tool usability
  - type: InternalOrgan
    intCap: 30
    integrity: 30
    integrityThresholds:
      Normal: 30
      Damaged: 12
      Destroyed: 0

- type: entity
  abstract: true
  parent: BaseAction
  id: BaseAugmentAction
  components:
  - type: InstantAction
    event: !type:AugmentActionEvent
