- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 1h # Trauma, was 5
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  guides: # Trauma
  - Forensics
  - Security
  access:
  - Security
  - Brig
  - Maintenance
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # Trauma
    components:
    - type: SecurityStaff

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    #gloves: ClothingHandsGlovesForensic - Goobstation, moved to loadouts
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
    - ClothingMaskGasSecurity # Goobstation

- type: chameleonOutfit
  id: DetectiveChameleonOutfit
  job: Detective
  hasMindShield: true
  equipment:
    head: ClothingHeadHatFedoraBrown
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckTieDet
    gloves: ClothingHandsGlovesForensic
