// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.Phones;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Phones.UI;

[GenerateTypedNameReferences]
public sealed partial class ChangePhoneName : FancyWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;
    public event Action<string>? OnTextChanged;
    public event Action<string>? OnCategoryChanged;
    public ChangePhoneName()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        FillCategories();
        MessageEdit.OnTextChanged += _ => OnTextChanged?.Invoke(MessageEdit.Text);
        CategoryOption.OnItemSelected += args =>
        {
            CategoryOption.SelectId(args.Id);
            var selectedText = CategoryOption.GetItemMetadata(args.Id)?.ToString() ?? "hidden";
            OnCategoryChanged?.Invoke(selectedText);
        };
    }

    private void FillCategories()
    {
        var sortedList = _prototype.EnumeratePrototypes<PhoneCategoryPrototype>()
            .OrderBy(p => p.Index)
            .ToList();

        for (var i = 0; i < sortedList.Count; i++)
        {
            CategoryOption.AddItem(Loc.GetString(sortedList[i].Text));
            CategoryOption.SetItemMetadata(i, sortedList[i].ID);
        }
    }
}
