// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.Phones;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Phones.UI;

[GenerateTypedNameReferences]
public sealed partial class PhoneMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;
    public event Action<int>? OnKeypadButtonPressed;
    public event Action<int>? OnPhoneBookButtonPressed;
    public event Action? OnClearButtonPressed;
    public event Action? OnEnterButtonPressed;

    private readonly Dictionary<string, Control> _categoryContainers = new();

    public PhoneMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        FillKeypadGrid();
        FillCategories();
    }

    private void FillKeypadGrid()
    {
        // add 3 rows of keypad buttons (1-9)
        for (var i = 1; i <= 9; i++)
        {
            AddKeypadButton(i);
        }

        // clear button
        var clearBtn = new Button()
        {
            Text = "C"
        };
        clearBtn.OnPressed += _ => OnClearButtonPressed?.Invoke();
        KeypadGrid.AddChild(clearBtn);

        // zero button
        AddKeypadButton(0);

        // enter button
        var enterBtn = new Button()
        {
            Text = "D"
        };
        enterBtn.OnPressed += _ => OnEnterButtonPressed?.Invoke();
        KeypadGrid.AddChild(enterBtn);
    }

    private void AddKeypadButton(int i)
    {
        var btn = new Button()
        {
            Text = i.ToString()
        };

        btn.OnPressed += _ => OnKeypadButtonPressed?.Invoke(i);
        KeypadGrid.AddChild(btn);
    }

    private void FillCategories()
    {
        var sorted = _prototype.EnumeratePrototypes<PhoneCategoryPrototype>()
            .OrderBy(p => p.Index)
            .ToList();

        foreach (var prototype in sorted)
        {
            if (prototype.HideInPhonebook)
                continue;

            var container = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            var body = new CollapsibleBody();
            body.AddChild(container);

            var collapsible = new Collapsible();
            collapsible.AddChild(new CollapsibleHeading { Title = Loc.GetString(prototype.Text) });
            collapsible.AddChild(body);

            PhoneBookContainer.AddChild(collapsible);
            _categoryContainers[prototype.ID] = container;
        }
    }

    public void ClearPhoneBook()
    {
        foreach (var container in _categoryContainers.Values)
        {
            container.DisposeAllChildren();
        }
    }

    public void AddPhoneBookLabel(string name, string category, int phonenumber)
    {
        if (!_categoryContainers.TryGetValue(category, out var container))
            return;

        var btn = new Button() { Text = Loc.GetString("phonebook-format", ("name", name), ("phonenumber", phonenumber)) };
        btn.OnPressed += _ => OnPhoneBookButtonPressed?.Invoke(phonenumber);
        container.AddChild(btn);
    }
}
