# SPDX-License-Identifier: AGPL-3.0-or-later

- type: cargoProduct
  id: SecurityWeaponLaserSidearm
  icon:
    sprite: _Trauma/Objects/Weapons/Guns/Battery/laser_pistor.rsi
    state: icon
  product: CrateSecurityWeaponLaserSidearm
  cost: 3600
  category: cargoproduct-category-name-armory
  group: market

- type: cargoProduct
  id: SecurityGunpowderCrate
  icon:
    sprite: _Trauma/Objects/Storage/gunpowderbottle.rsi
    state: closed
  product: CrateSecurityGunpowder
  cost: 15000
  category: cargoproduct-category-name-armory
  group: market

- type: cargoProduct
  id: SecuritySkillChips
  icon:
    sprite: _Trauma/Objects/Specific/brain_chips.rsi
    state: icon
  product: CrateSkillChipsSec
  cost: 8000
  category: cargoproduct-category-name-security
  group: market
