// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.Timing;
using System.Linq;

namespace Content.Trauma.Client.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class NetBandwidthPanel : PanelContainer
{
    private IGameTiming _timing;
    private INetManager _net;

    private TimeSpan _nextUpdate;
    private TimeSpan _updateDelay = TimeSpan.FromSeconds(1);
    private Dictionary<Type, long> _diff = new();
    private Dictionary<Type, long> _lastUsage = new();

    public NetBandwidthPanel(IGameTiming timing, INetManager net)
    {
        RobustXamlLoader.Load(this);

        _timing = timing;
        _net = net;

        _lastUsage = _net.MessageBandwidthUsage.ToDictionary();

        ResetButton.OnPressed += _ => _net.ResetBandwidthMetrics();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var now = _timing.CurTime;
        if (!VisibleInTree || now < _nextUpdate)
            return;

        _nextUpdate = now + _updateDelay;

        var current = _net.MessageBandwidthUsage;
        _diff.Clear();
        foreach (var (type, value) in current)
        {
            var change = value - _lastUsage.GetValueOrDefault(type);
            if (change != 0)
                _diff[type] = change;
        }
        _lastUsage = current.ToDictionary();

        const int kibibyte = 1024;

        var diff = _diff
            .OrderByDescending(p => p.Value)
            .Select(p => $"{TypeAbbreviation.Abbreviate(p.Key)}: {p.Value / kibibyte} KiB/s");
        DiffLabel.Text = string.Join('\n', diff);
        var total = current
            .OrderByDescending(p => p.Value)
            .Select(p => $"{TypeAbbreviation.Abbreviate(p.Key)}: {p.Value / kibibyte} KiB total");
        TotalLabel.Text = total.Count() == 0
            ? "RobustToolbox removes bandwidth information on release, you must compile the game yourself to see it!"
            : string.Join('\n', total);
    }

    public void Toggle()
    {
        Visible = !Visible;
    }
}
