// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Trauma.Shared.Heretic.Ui;
using Robust.Shared.Input;

namespace Content.Trauma.Client.Heretic.UI;

[GenerateTypedNameReferences]
public sealed partial class GhoulRecallWindow : FancyWindow
{
    public event Action<NetEntity>? OnItemSelected;

    public GhoulRecallWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Ghouls.SearchBar = SearchBar;
        Ghouls.DataFilterCondition += DataFilterCondition;
        Ghouls.GenerateItem += GenerateButton;
        Ghouls.ItemKeyBindDown += (args, data) =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
                OnItemSelected?.Invoke(((GhoulRecallListData) data).Data.Ent);
        };
    }

    private bool DataFilterCondition(string filter, ListData data)
    {
        if (data is not GhoulRecallListData { Data.Name: var name })
            return false;

        return string.IsNullOrEmpty(filter) || name.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not GhoulRecallListData cast)
            return;

        button.AddChild(new GhoulRecallItem(cast.Data.Name, cast.Data.Distance));
    }

    public void Populate(List<GhoulRecallData> ghouls)
    {
        if (ghouls.Count == 0)
        {
            Ghouls.Visible = false;
            SearchBar.Visible = false;
            NoGhoulsLabel.Visible = true;
            SetSizeAfterUpdate(NoGhoulsLabel.Text?.Length ?? 20, 1);
            return;
        }

        Ghouls.Visible = true;
        SearchBar.Visible = true;
        NoGhoulsLabel.Visible = false;

        var longestEntry = 0;
        List<GhoulRecallListData> listData = new();
        foreach (var ghoul in ghouls)
        {
            longestEntry = Math.Max(longestEntry, ghoul.Name.Length);
            listData.Add(new GhoulRecallListData(ghoul));
        }

        listData.Sort(Compare);

        Ghouls.PopulateList(listData);
        SetSizeAfterUpdate(longestEntry, listData.Count);

        return;

        int Compare(GhoulRecallListData x, GhoulRecallListData y)
        {
            if (x.Data.Distance is not { } a)
                return 1;

            if (y.Data.Distance is not { } b)
                return -1;

            return b.CompareTo(a);
        }
    }

    private void SetSizeAfterUpdate(int longestEntryLength, int contentCount)
    {
        SetSize = new Vector2(Math.Clamp((longestEntryLength + 10) * 12, 250, 400),
            Math.Clamp(contentCount * 50, 150, 350));
    }
}

public record GhoulRecallListData(GhoulRecallData Data) : ListData;
