// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.Virology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Trauma.Client.Virology.UI;

[GenerateTypedNameReferences]
public sealed partial class DiseaseDnaSamplerWindow : FancyWindow
{
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private EntityUid _uid;
    private EntProtoId? _disease;
    private int _dnas;

    public event Action? OnCreateInjector;

    public DiseaseDnaSamplerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CreateInjector.OnPressed += _ => OnCreateInjector?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateSampler();
    }

    public void SetOwner(EntityUid uid)
    {
        _uid = uid;
        UpdateSampler();
    }

    private void UpdateSampler()
    {
        if (!_ent.TryGetComponent<DiseaseDnaSamplerComponent>(_uid, out var comp))
            return;

        if (comp.Disease != _disease)
        {
            _disease = comp.Disease;
            DiseaseLabel.Text = _disease is {} disease
                ? Loc.GetString("disease-dna-sampler-disease", ("name", _proto.Index(disease).Name))
                : Loc.GetString("disease-dna-sampler-no-disease");
        }
        if (comp.TargetDnas.Count != _dnas)
        {
            _dnas = comp.TargetDnas.Count;
            TargetsLabel.Text = _dnas > 0
                ? string.Join("\n", comp.TargetDnas)
                : Loc.GetString("disease-dna-sampler-no-dna");
        }
        CreateInjector.Disabled = comp.Disease == null || comp.TargetDnas.Count == 0;
    }
}
