// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Trauma.Shared.Abductor;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Trauma.Client.Abductor.UI;

[GenerateTypedNameReferences]
public sealed partial class AbductorTaskWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IResourceCache _cache = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    public event Action? OnScan;
    public event Action? OnComplete;

    private EntityUid _uid;
    private EntityUid? _subject;
    private int? _completed;
    private int? _tasks;

    public AbductorTaskWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Ayylmao.FontOverride = _cache.NotoStack2ElectricBoogaloo("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 40);

        ScanButton.OnPressed += _ => OnScan?.Invoke();
    }

    public void SetOwner(EntityUid uid)
    {
        if (!_entMan.TryGetComponent<AbductorTaskTabletComponent>(uid, out var comp))
            return;

        _uid = uid;
        Update(comp);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (!_entMan.TryGetComponent<AbductorTaskTabletComponent>(_uid, out var comp))
            return;

        Update(comp);
    }

    private void Update(AbductorTaskTabletComponent comp)
    {
        UpdateSubject(_entMan.GetEntity(comp.Target));
    }

    private void UpdateSubject(EntityUid? subject)
    {
        if (subject != _subject)
        {
            _subject = subject;
            UpdateSubject();
        }

        if (!_entMan.TryGetComponent<AbductorSubjectComponent>(subject, out var comp))
        {
            if (_completed != null)
            {
                _completed = null;
                _tasks = null;
                UpdateVisibility();
            }
            return;
        }

        if (comp.CompletedCount != _completed || comp.Tasks.Count != _tasks)
        {
            _completed = comp.CompletedCount;
            _tasks = comp.Tasks.Count;
            UpdateTasks(comp.Tasks, comp.CompletedCount);
            UpdateVisibility();
        }
    }

    private void UpdateSubject()
    {
        if (_subject is {} subject)
        {
            var name = _entMan.GetComponent<MetaDataComponent>(subject).EntityName;
            var species = _proto.Index(_entMan.GetComponent<HumanoidProfileComponent>(subject).Species);
            SubjectName.Text = Loc.GetString("abductor-task-window-subject", ("name", name));
            SubjectSpecies.Text = Loc.GetString("abductor-task-window-species", ("species", Loc.GetString(species.Name)));
        }
        SpriteView.SetEntity(_subject);
        UpdateVisibility();
    }

    private void UpdateTasks(List<ProtoId<AbductorTaskPrototype>> tasks, int completedCount)
    {
        TasksContainer.RemoveAllChildren();
        for (int i = 0; i < tasks.Count; i++)
        {
            var task = _proto.Index(tasks[i]);
            var completed = completedCount > i;
            var current = completedCount == i;
            var button = new AbductorTaskButton(task.Name, completed, current);
            button.OnPressed += _ => OnComplete?.Invoke();
            TasksContainer.AddChild(button);
        }
    }

    private void UpdateVisibility()
    {
        var hasSubject = _subject != null;
        var scanned = _completed != null;
        LinkContainer.Visible = !hasSubject;
        ScanContainer.Visible = hasSubject && !scanned;
        ScannedContainer.Visible = hasSubject && scanned;
    }
}
