// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Goobstation.UIKit.UserActions.Controls;
using Content.Trauma.Client.UserActions.Tabs;
using Content.Trauma.Shared.MartialArts.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;

namespace Content.Trauma.Client.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class MartialArtsTabControl : BaseTabControl
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private ISharedPlayerManager _player = default!;
    private readonly KnowledgeSystem _knowledge;
    private readonly SpriteSystem _sprite;

    public MartialArtsTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _entMan.System<KnowledgeSystem>();
        _sprite = _entMan.System<SpriteSystem>();
    }

    public override bool UpdateState()
    {
        // TODO: fix scroll when this happens ugh
        MartialArtsList.RemoveAllChildren();

        if (_player.LocalEntity is not {} player ||
            _knowledge.GetContainer(player) is not {} brain ||
            _knowledge.GetKnowledgeWith<MartialArtsKnowledgeComponent>(brain) is not {} arts)
            return false;

        var button = CreateMartialArtsButton(null);
        MartialArtsList.AddChild(button);

        foreach (var martialArt in arts)
        {
            button = CreateMartialArtsButton(martialArt);
            MartialArtsList.AddChild(button);
        }
        return true;
    }


    private IconButton CreateMartialArtsButton(Entity<MartialArtsKnowledgeComponent>? martialArt)
    {
        var (name, proto) = _entMan.TryGetComponent<MetaDataComponent>(martialArt, out var meta)
            ? (meta.EntityName, meta.EntityPrototype?.ID)
            : (Loc.GetString("no-martial-art"), null);

        var button = new IconButton(name);
        if (martialArt?.Comp.Icon is {} icon)
            button.Icon.Texture = _sprite.Frame0(icon);
        button.OnPressed += _ => _knowledge.ChangeMartialArt(proto);

        return button;
    }
}
