- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 5h
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 2.5h
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10h
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  antagAdvantage: 75 # Trauma
  guides: # Trauma
  - Cargo
  - Command
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  # <Trauma>
  - !type:OrganChipsSpecial
    chips:
    - SkillChipQuartermaster
  # </Trauma>
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      # <Trauma>
      - type: Condemned # Nanotrasen owns your soul pal.
        soulOwnedNotDevil: true
      # </Trauma>
      - type: CommandStaff
      - type: QuartermasterTraining

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetAltCargo # Goobstation
    belt: BoxFolderClipboardThreePapers
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: QuartermasterChameleonOutfit
  job: Quartermaster
  hasMindShield: true
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
