- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconCBURN"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear # Goobstation - Start - Sol
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Executive Access!
    eyes: ClothingEyesGlassesMedSec # Better glasses
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    id: CBURNPDA # Todo - Replace it.
    pocket1: InfectionScannerCburn # Goob
    pocket2: WeaponShotgunSawn # Trauma - was WeaponLaserGun
    belt: ClothingBeltSecurityFilled # No shotgun, no bandolier.
  storage:
    back:
    - WeaponEnergyRifle # Trauma
    - EnergyMagRifleLethal # Trauma
    - EnergyMagRifleLethal # Trauma
    - EnergyMagRifleLethal # Trauma
    - EnergyMagRifleOverchargeLethal # Trauma
    - EnergyMagRifleOverchargeLethal # Trauma
    - BoxLethalshot
    - AmbuzolPlusMedipen # Injectors are cooler.
    - AmbuzolMedipen # Injectors are cooler.
    - AmbuzolMedipen # Injectors are cooler.
    - MedkitCombatFilled # Ah yes, let's send them in with ZERO meds. Good luck!
    - CburnSpear # SPEAAR
# Goobstation - End - Sol

- type: chameleonOutfit
  id: CBURNChameleonOutfit
  job: CBURN
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetCBURN
    neck: ClothingNeckScarfStripedBrown
