// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.CosmicCult;
using Content.Trauma.Shared.CosmicCult.Components;
using Content.Trauma.Shared.CosmicCult.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Trauma.Client.CosmicCult.UI.CosmicShop;

[GenerateTypedNameReferences]
public sealed partial class CosmicShopMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IGameTiming _timing = default!;

    // All influence prototypes
    private readonly IEnumerable<InfluencePrototype> _influencePrototypes;
    public Action<ProtoId<InfluencePrototype>>? OnGainButtonPressed;
    public Action? OnLevelUpConfirmed;
    public Action? OnRespecConfirmed;
    private InfluencePrototype? _selectedInfluence = null;
    private TimeSpan? _timer;
    private TimeSpan _respecLockTime = TimeSpan.FromSeconds(0.8);
    private TimeSpan _respecResetTime = TimeSpan.FromSeconds(4);

    public CosmicShopMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _influencePrototypes = _proto.EnumeratePrototypes<InfluencePrototype>();
        LevelUpConfirm.OnPressed += _ => OnLevelUpConfirmed?.Invoke();
        RespecButton.OnPressed += _ => RespecButtonPressed();

        CultProgressBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = new Color(15, 17, 30) };
        CultProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = new Color(91, 62, 124) };
    }

    public void UpdateState(CosmicCultComponent state)
    {
        UpdateBar(state);
        UpdateEntropy(state);
        UpdateInfluences(state);
        UpdateLevelupConfirmation(state);
        if (_selectedInfluence is { } influence) OpenInfluenceDetails(influence, state);
    }

    /// <summary>
    ///     Updates the progress bar
    /// </summary>
    private void UpdateBar(CosmicCultComponent state)
    {
        var percentComplete = 100f * ((float) (state.TotalEntropy - state.EntropyRequirementOffset) / state.EntropyForNextLevel);

        percentComplete = Math.Min(percentComplete, 100f);

        if (state.EntropyLocked) percentComplete = 100f;

        CultProgressBar.Value = percentComplete;

        ProgressBarPercentage.Text = Loc.GetString("cosmic-shop-interface-progress-bar", ("percentage", percentComplete.ToString("0")));
    }

    /// <summary>
    ///     Updates the entropy fields
    /// </summary>
    private void UpdateEntropy(CosmicCultComponent state)
    {
        var entropyToNextStage = Math.Max(state.EntropyForNextLevel - (state.TotalEntropy - state.EntropyRequirementOffset), 0);

        if (state.EntropyLocked) entropyToNextStage = 0;

        AvailableEntropy.Text = Loc.GetString("cosmic-shop-interface-entropy-value", ("infused", state.EntropyBudget));
        EntropyUntilNextStage.Text = Loc.GetString("cosmic-shop-interface-entropy-value", ("infused", entropyToNextStage));
        CultisttUntilNextCultStage.Text = state.CultistsForNextLevel.ToString();

        if (state.RespecsAvailable <= 0 || state.OwnedInfluences.Count <= 0)
        {
            RespecText.Text = Loc.GetString(state.RespecsAvailable <= 0 ? "cosmic-shop-interface-respec-no-rift" : "cosmic-shop-interface-respec-no-influence");
            RespecButton.Disabled = true;
            RespecButton.Modulate = Color.Gray;
        }
        else
        {
            if (_timer != null) return;
            RespecText.SetMessage(Loc.GetString("cosmic-shop-interface-respec-amount", ("count", state.RespecsAvailable)));
            RespecButton.Disabled = false;
            RespecButton.Modulate = Color.White;
        }
    }

    /// <summary>
    ///    Update all the influence thingies
    /// </summary>
    private void UpdateInfluences(CosmicCultComponent state)
    {
        var influenceButtons = new List<InfluenceButtonContainer>();
        foreach (var influenceProto in _influencePrototypes)
        {
            var uiBoxState = GetUIBoxStateForInfluence(influenceProto, state);
            var influenceButton = new InfluenceButtonContainer(influenceProto, uiBoxState);
            influenceButton.OnDetailButtonPressed += () => OpenInfluenceDetails(influenceProto, state);
            influenceButtons.Add(influenceButton);
        }

        Control[] containers = [Level0, Level1, Level2, Level3];
        foreach (var container in containers)
            container.RemoveAllChildren();
        foreach (var box in influenceButtons.OrderBy(box => box.Proto.Cost))
            containers[box.Proto.Tier].AddChild(box);
    }

    private void UpdateLevelupConfirmation(CosmicCultComponent state)
    {
        LevelUpConfirmation.Visible = state.LevelUpAwaitingConfirmation;
        if (!state.LevelUpAwaitingConfirmation) return;
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("cosmic-shop-interface-consequences"));
        msg.PushNewline();
        msg.AddMarkupOrThrow(Loc.GetString("cosmic-shop-interface-consequence-level" + (state.CurrentLevel + 1).ToString()));
        // It's hardcoded to check if next tier is tier 2, because tier 2 no longer has any effects, and I'm too lazy to make a generic check for that
        // This will be discarded in rework part 2 anyway.
        if ( state.CultistsForNextLevel <= 1 && state.CurrentLevel == state.CultTier && state.CultTier != 1) // Tierup on normal conditions
        {
            msg.PushNewline();
            msg.AddMarkupOrThrow(Loc.GetString("cosmic-shop-interface-consequence-tier" + (state.CultTier + 1).ToString()));
        }
        if (state.CurrentLevel > state.CultTier && state.CultTier != 1) // Speedrun tierup
        {
            msg.PushNewline();
            msg.AddMarkupOrThrow(Loc.GetString("cosmic-shop-interface-consequence-tier" + (state.CurrentLevel).ToString()));
        }
        ConsequenceLabel.SetMessage(msg, Color.FromHex("#4CA7AD"));
    }

    /// <summary>
    ///    Show all the details of the selected influence
    /// </summary>
    private void OpenInfluenceDetails(InfluencePrototype influenceProto, CosmicCultComponent state)
    {
        _selectedInfluence = influenceProto;
        InfluenceInfoContainer.RemoveAllChildren();
        var uiBoxState = GetUIBoxStateForInfluence(influenceProto, state);
        var influenceBox = new InfluenceUIBox(influenceProto, uiBoxState);
        InfluenceInfoContainer.AddChild(influenceBox);
        influenceBox.OnGainButtonPressed += () => OnGainButtonPressed?.Invoke(influenceProto.ID);
    }

    private InfluenceUIBox.InfluenceUIBoxState GetUIBoxStateForInfluence(InfluencePrototype influence, CosmicCultComponent state)
    {

        var unlocked = state.UnlockedInfluences.Contains(influence.ID);
        var owned = state.OwnedInfluences.Contains(influence);

        //more verbose than it needs to be, but it reads nicer
        if (owned)
            return InfluenceUIBox.InfluenceUIBoxState.Owned;

        //TODO: dependency check when skill trees are real

        //if it's unlocked, do we have enough entropy to buy it?
        if (unlocked)
            return influence.Cost > state.EntropyBudget
                ? InfluenceUIBox.InfluenceUIBoxState.UnlockedAndNotEnoughEntropy
                : InfluenceUIBox.InfluenceUIBoxState.UnlockedAndEnoughEntropy;

        return InfluenceUIBox.InfluenceUIBoxState.Locked;
    }

    private void RespecButtonPressed()
    {
        if (_timer == null)
        {
            _timer = _timing.CurTime;
            RespecButton.Modulate = Color.Red;
            RespecButton.Text = Loc.GetString("cosmic-shop-interface-respec-confirmation");
            RespecButton.Disabled = true; // Prevent accidental double-clicking for .5 seconds
        }
        else
        {
            _timer = null;
            OnRespecConfirmed?.Invoke();
            RespecButton.Disabled = true; // Lock the button until next state arrives
            RespecButton.Modulate = Color.Gray;
            RespecButton.Text = Loc.GetString("cosmic-shop-interface-respec-button");
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (!VisibleInTree || _timer is not { } timer)
        {
            return;
        }
        if (timer + _respecLockTime <= _timing.CurTime)
        {
            RespecButton.Disabled = false;
        }
        if (timer + _respecResetTime <= _timing.CurTime)
        {
            RespecButton.Modulate = Color.White;
            RespecButton.Text = Loc.GetString("cosmic-shop-interface-respec-button");
            _timer = null;
        }
    }
}
