// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared.CosmicCult.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.CosmicCult.UI.CosmicShop;

[GenerateTypedNameReferences]
public sealed partial class InfluenceUIBox : BoxContainer
{
    [Dependency] private IEntityManager _entityManager = default!;

    private readonly SpriteSystem _sprite;

    public Action? OnGainButtonPressed;

    public enum InfluenceUIBoxState : byte
    {
        UnlockedAndEnoughEntropy = 0,
        UnlockedAndNotEnoughEntropy = 1,
        Owned = 2,
        Locked = 3,
    }

    public readonly InfluenceUIBoxState State;
    public readonly InfluencePrototype Proto;

    public InfluenceUIBox(InfluencePrototype influenceProto, InfluenceUIBoxState state)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entityManager.System<SpriteSystem>();

        InfluenceIcon.Texture = _sprite.Frame0(influenceProto.Icon);
        NameLabel.SetMessage(Loc.GetString(influenceProto.Name), Color.FromHex("#4CA7AD"));

        State = state;
        Proto = influenceProto;

        switch (state)
        {
            case InfluenceUIBoxState.Owned:
                Status.Text = Loc.GetString("cosmic-shop-interface-influences-owned");

                GainButton.Disabled = true;
                GainButton.Modulate = Color.Green;
                GainButton.Label.Text = Loc.GetString("cosmic-shop-interface-influences-purchased");
                GainButton.ToolTip = Loc.GetString("cosmic-shop-interface-influences-owned-tooltip");

                break;

            case InfluenceUIBoxState.UnlockedAndEnoughEntropy:
                Status.Text = Loc.GetString("cosmic-shop-interface-influences-unlocked");

                GainButton.Disabled = false;

                break;

            case InfluenceUIBoxState.UnlockedAndNotEnoughEntropy:
                Status.Text = Loc.GetString("cosmic-shop-interface-influences-unlocked");

                GainButton.Disabled = false;
                GainButton.Modulate = Color.Gray;
                GainButton.ToolTip = Loc.GetString("cosmic-shop-interface-influences-unlocked-not-enough-entropy-tooltip", ("entropy", influenceProto.Cost));
                break;

            case InfluenceUIBoxState.Locked:
                // TODO: check for dependencies. If some are missing, replace the text accordingly.
                Status.Text = Loc.GetString("cosmic-shop-interface-influences-locked");

                GainButton.Disabled = true;
                GainButton.Modulate = Color.Gray;
                GainButton.Label.Text = Loc.GetString("cosmic-shop-interface-influences-locked");
                GainButton.ToolTip = Loc.GetString("cosmic-shop-interface-influences-locked-tooltip");

                break;
        }

        Type.Text = Loc.GetString(influenceProto.Passive ? "influence-type-passive" : "influence-type-active");
        Cost.Text = influenceProto.Cost.ToString();
        Description.SetMessage(Loc.GetString(influenceProto.Description));
        if (influenceProto.EmpoweredDescription is { } desc)
        {
            UpgradeDescription.SetMessage(Loc.GetString(desc), Color.FromHex("#4CA7AD"));
            UpgradeDescription.Visible = true;
        }

        GainButton.OnPressed += _ => OnGainButtonPressed?.Invoke();
    }
}
