# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antagSmite
  id: Changeling
  antag: Changeling
  rule: Changeling
  ruleComp: ChangelingRule
  icon:
    sprite: _Goobstation/Changeling/changeling_abilities.rsi
    state: transform
  whitelist:
    components:
    - Body
  blacklist:
    components:
    - Silicon # no
    - BorgChassis
