# Hunters
  # SpacePol
- type: startingGear
  id: HunterAntagGear
  equipment:
    head: ClothingHeadHelmetSwat # maybe keep justice for shits and giggles?
    eyes: ClothingEyesGlassesSecurity
    neck: Dinkystar
    mask: ClothingHunterMaskGasSwat
    jumpsuit: ClothingUniformJumpsuitNanotrasen
    outerClothing: ClothingOuterArmourDurathread
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsJackFilled
    belt: ClothingBeltSecurityFilled
    id: HunterPDA
    pocket1: WeaponPistolMk58
    pocket2: WeaponLaserSidearm
    ears: ClothingHeadsetAltHunter
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSlotsSecurity
    - MagazinePistol
    - ForensicScanner
    - MedkitCombat

- type: antagSpecifier
  id: FugitiveHunter
  spawnerPrototype: SpawnPointGhostRoleHunter
  startingGear: HunterAntagGear
  briefing:
    text: hunter-role-greeting
    color: red
  components:
  - type: NpcFactionMember
    factions:
    - Syndicate
  - type: AutoImplant
    implants:
    - FakeMindShieldImplant
    - DeathAcidifierImplant
  - type: RandomMetadata
  mindRoles:
  - MindRoleGhostRoleHunter

# Fugitives
  # Convict
- type: startingGear
  id: FugitiveAntagGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    belt: ClothingBeltStorageWaistbag
    id: IDCardTide
    pocket1: CombatKnife
    pocket2: SoapSyndie
  inhand:
  - SatchelFugitive
  storage:
    belt:
    - BarberScissors
    - Telecrystal25

- type: antagSpecifier
  id: Fugitive
  spawnerPrototype: SpawnPointGhostRoleFugitive
  startingGear: FugitiveAntagGear
  briefing:
    text: fugitive-role-greeting
    color: red
  components:
  - type: NpcFactionMember
    factions:
    - Syndicate
  - type: AutoImplant
    implants:
    - UplinkImplant
  - type: RandomMetadata
  - type: EmitSoundOnSpawn # fell out of the ceiling
    sound: /Audio/Effects/clang.ogg
  mindRoles:
  - MindRoleGhostRoleFugitive
