- type: antag
  id: Insurgent
  name: roles-antag-insurgent-name
  objective: roles-antag-insurgent-objective
  antagonist: true
  setPreference: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 5h
  guides: [ Insurgents ]

- type: antagSpecifier
  id: Insurgent
  spawnerPrototype: GhostRoleSpawnerInsurgent
  startingGear: Insurgent
  unequipOldGear: true
  prefRoles: [ Insurgent ]
  mindRoles: [ MindRoleInsurgent ]
  roleLoadout: [ RoleSurvivalStandard ]
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true

- type: startingGear
  id: Insurgent
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackSatchel
    mask: ClothingMaskGas
    head: ClothingHeadHatWelding
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesColorYellowBudget
    shoes: ClothingShoesColorBlack
    pocket2: FlashlightLantern
    belt: ClothingBeltUtilityFilled
    neck: ClothingNeckBombCollarBroken

- type: antagSmite
  id: Insurgent
  antag: Insurgent
  rule: Insurgency
  ruleComp: InsurgencyRule
  icon:
    sprite: Clothing/Mask/gas.rsi
    state: icon
