// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared.EntityEffects;
using Content.Trauma.Shared.Tools;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Tools.UI;

[GenerateTypedNameReferences]
public sealed partial class DebugEffectStickWindow : FancyWindow
{
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    public event Action<string?>? OnSetEffect;

    public DebugEffectStickWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Effects.OnItemSelected += args =>
        {
            var effect = (string?) args.Button.GetItemMetadata(args.Id);
            args.Button.Select(args.Id);
            OnSetEffect?.Invoke(effect);
        };
    }

    public void SetOwner(EntityUid uid)
    {
        if (!_ent.TryGetComponent<DebugEffectStickComponent>(uid, out var comp))
            return;

        var selected = comp.Effect;
        Effects.AddItem("None");
        var effects = new List<string>();
        foreach (var proto in _proto.EnumeratePrototypes<EntityEffectPrototype>())
        {
            effects.Add(proto.ID);
        }

        if (selected == null)
            Effects.Select(0);

        effects.Sort();

        foreach (var effect in effects)
        {
            var idx = Effects.ItemCount;
            Effects.AddItem(effect);
            Effects.SetItemMetadata(idx, (string) effect);
            if (effect == selected)
                Effects.Select(idx);
        }
    }
}
