- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    # - !type:OverallPlaytimeRequirement
    #   time: 2.5h
    - !type:DepartmentTimeRequirement # Trauma
      department: Security
      time: 1h
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hop
  access:
  #- Service # Trauma - piss off
  - Lawyer
  - Brig
  - Maintenance
  # <Trauma>
  guides:
  - SpaceLaw
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipLawyer
  # Everyone knows lawyers are soulless.
  - !type:AddComponentSpecial
    components:
    - type: Condemned
      soulOwnedNotDevil: true
    - type: Lawyer
  # </Trauma>

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
