- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconBrutalize
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_brutalize

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconDemote
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_demote
