// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.GameTicking.Managers;
using Content.Shared.GameTicking;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Trauma.Client.RoundEndCredits;

[GenerateTypedNameReferences]
public sealed partial class EndRoundCreditsControl : ScrollContainer
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private readonly ClientGameTicker _gameTicker;

    private static readonly ResPath Logo = new("/Textures/Logo/logo.png");
    private static readonly ResPath Pixellari = new("/Fonts/_Trauma/Pixellari.ttf");
    private static readonly ResPath GrandPixel = new("/Fonts/_Trauma/Grand9K_Pixel.ttf");

    private const int SmallFontSize = 10;
    private const int NormalFontSize = 16;
    private const int BigFontSize = 24;
    private const int HeaderFontSize = 42;

    public EndRoundCreditsControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
    }

    public void Populate(RoundEndMessageEvent message, IResourceCache cache, IPrototypeManager proto, string shoutout, bool debug = false)
    {

        var stationName = "Unknown";

        foreach (var (_, name) in _gameTicker.StationNames)
        {
            stationName = name;
            break;
        }

        var headerFont = new VectorFont(cache.GetResource<FontResource>(Pixellari), HeaderFontSize);
        var bigFont = new VectorFont(cache.GetResource<FontResource>(Pixellari), BigFontSize);
        var playerNameFont = new VectorFont(cache.GetResource<FontResource>(GrandPixel), SmallFontSize);

        var texture = cache.GetResource<TextureResource>(Logo);

        var serverImage = new TextureRect
        {
            Margin = new Thickness(0, 1000, 0, 500),
            Texture = texture,
        };

        var thanksForPlaying = new Label
        {
            Text = Loc.GetString("round-end-credits-trauma-thankyou"),
            Align = Label.AlignMode.Center,
            FontOverride = bigFont,
            Margin = new Thickness(0, 500, 0, 1500),
        };

        // Image mgsv episode number and jargon
        ServerImageBox.AddChild(serverImage);
        EpisodeNumber.Text = Loc.GetString("round-end-credits-trauma-episode", ("roundid", message.RoundId), ("title", message.GamemodeTitle));
        IntroJargonLabel.Text = Loc.GetString("round-end-credits-trauma-jargon", ("station", stationName));

        // The fonts
        EpisodeNumber.FontOverride = bigFont;
        IntroJargonLabel.FontOverride = bigFont;
        ShoutOutLabel.FontOverride = bigFont;
        CastLabel.FontOverride = bigFont;

        // Hideo Kojima
        ShoutOutLabel.Text = Loc.GetString("round-end-credits-trauma-director", ("shoutout", shoutout));
        CastLabel.Text = Loc.GetString("round-end-credits-trauma-cast");

        // Add the list of people with no sprite
        foreach (var player in message.AllPlayersEndInfo)
        {
            if (player.PlayerICName != null)
                MainCreditVBox.AddChild(MakePlayerInfoBox(player, playerNameFont, Color.White, true, false));
        }

        var sortedDepartments = proto.EnumeratePrototypes<DepartmentPrototype>()
            .OrderByDescending(p => p.Weight)
            .ToList();

        // Add each department
        foreach (var department in sortedDepartments)
        {
            MainCreditVBox.AddChild(MakeDepartmentContainer(department, headerFont, playerNameFont, message.AllPlayersEndInfo, debug));
        }

        var antags = proto.EnumeratePrototypes<AntagPrototype>()
            .OrderBy(p => p.Name)
            .ToList();

        // Add antags
        foreach (var antag in antags)
        {
            var antagBox = MakeAntagBox(message.AllPlayersEndInfo, playerNameFont, headerFont, antag, cache);
            if (antagBox is { })
                MainCreditVBox.AddChild(antagBox);
        }

        var lastwords = message.AllPlayersEndInfo.Any(p => p.LastWords != null);

        if (lastwords)
        {
            MainCreditVBox.AddChild(MakeFamousLastWordsBox(bigFont));
            MainCreditVBox.AddChild(MakeLastWordsBox(playerNameFont, message.AllPlayersEndInfo));
        }

        MainCreditVBox.AddChild(thanksForPlaying);
    }

    public void AddKojimaBox(IResourceCache cache)
    {
        var normalFont = new VectorFont(cache.GetResource<FontResource>(Pixellari), NormalFontSize);
        var bigFont = new VectorFont(cache.GetResource<FontResource>(Pixellari), BigFontSize);
        MainCreditVBox.AddChild(MakeKojimaBox(normalFont, bigFont));
    }

    private BoxContainer MakePlayerInfoBox(RoundEndMessageEvent.RoundEndPlayerInfo playerInfo, VectorFont font, Color color, bool fullInfo = false, bool addSprite = true)
    {
        var box = new BoxContainer
        {
            Align = BoxContainer.AlignMode.Center,
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            MaxHeight = 100,
        };

        if (playerInfo.PlayerNetEntity is {} && addSprite)
        {
            box.AddChild(new SpriteView(playerInfo.PlayerNetEntity.Value, IoCManager.Resolve<IEntityManager>())
            {
                OverrideDirection = Direction.South,
                VerticalAlignment = VAlignment.Center,
                SetSize = new Vector2(64, 64),
                VerticalExpand = true,
                Stretch = SpriteView.StretchMode.Fill,
                Margin = new Thickness(10, 0, 10, 5),
                HorizontalAlignment = HAlignment.Center,
            });
        }

        var role = Loc.GetString(playerInfo.Role);
        var text = new Label
        {
            Name = playerInfo.PlayerICName,
            Text = fullInfo ? Loc.GetString("round-end-credits-trauma-player-name-role", ("name", playerInfo.PlayerICName ?? "Unknown"), ("role", role), ("player", playerInfo.PlayerOOCName)) : playerInfo.PlayerICName,
            Align = Label.AlignMode.Center,
            FontOverride = font,
            FontColorOverride = color,
            Margin = new Thickness(15, 0, 15, 15),
            HorizontalAlignment = HAlignment.Center,
        };

        box.AddChild(text);
        return box;
    }

    private BoxContainer MakeDepartmentContainer(DepartmentPrototype department, VectorFont fontHeader, VectorFont smallFont, RoundEndMessageEvent.RoundEndPlayerInfo[] players, bool debug)
    {
        var text = new Label
        {
            Text = Loc.GetString(department.Name),
            FontOverride = fontHeader,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = department.Color,
        };

        var boxH = new GridContainer
        {
            Columns = 11,
            HorizontalAlignment = HAlignment.Center,
        };

        var boxV = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 150, 0, 50),
        };

        boxV.AddChild(text);
        boxV.AddChild(boxH);

        foreach (var playerInfo in players)
        {
            var belongsToDepartment = playerInfo.JobPrototypes.Any(jobId =>
                department.Roles.Contains(new ProtoId<JobPrototype>(jobId)));

            if (belongsToDepartment)
                boxH.AddChild(MakePlayerInfoBox(playerInfo, smallFont, Color.White));

            if (debug)
            {
                for (var i = 0; i < 35; i++)
                {
                    boxH.AddChild(MakePlayerInfoBox(playerInfo, smallFont, Color.White));
                }
            }
        }

        return boxV;
    }

    private BoxContainer? MakeAntagBox(RoundEndMessageEvent.RoundEndPlayerInfo[] players, VectorFont smallfont, VectorFont headerFont, AntagPrototype antag, IResourceCache cache)
    {
        var boxH = new GridContainer
        {
            Columns = 11,
            HorizontalAlignment = HAlignment.Center,
        };

        var boxV = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Align = BoxContainer.AlignMode.Center,
            Margin = new Thickness(0, 150, 0, 50),
        };

        if (!string.IsNullOrWhiteSpace(antag.CreditImage.ToString())
            && antag.CreditImage != null
            && cache.TryGetResource<TextureResource>(antag.CreditImage.Value, out var texture))
        {
            boxV.AddChild(new TextureRect
            {
                Texture = texture,
                HorizontalAlignment = HAlignment.Center,
            });
        }
        else
        {
            boxV.AddChild(new Label
            {
                HorizontalAlignment = HAlignment.Center,
                Text = Loc.GetString(antag.Name),
                FontOverride = headerFont,
                FontColorOverride = antag.Color,
            });
        }

        boxV.AddChild(boxH);

        var playersInSection = false;

        foreach (var player in players)
        {
            if (!player.Antag)
                continue;

            foreach (var playerAntag in player.AntagPrototypes)
            {
                if (playerAntag == antag.ID && !antag.DontShowInCredits)
                {
                    boxH.AddChild(MakePlayerInfoBox(player, smallfont, antag.Color));
                    playersInSection = true;
                }
            }
        }

        return playersInSection ? boxV : null;
    }

    private BoxContainer MakeKojimaBox(VectorFont directorFont, VectorFont kojimaFont)
    {
        var vBox = new BoxContainer
        {
            Align = BoxContainer.AlignMode.Center,
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 0, 0, 300),
        };

        vBox.AddChild(new Label
        {
            Text = Loc.GetString("round-end-credits-trauma-created"),
            Align = Label.AlignMode.Center,
            FontOverride = directorFont,
        });

        vBox.AddChild(new Label
        {
            Text = Loc.GetString("round-end-credits-trauma-kojima"),
            Align = Label.AlignMode.Center,
            FontOverride = kojimaFont,
        });

        return vBox;
    }

    private BoxContainer MakeFamousLastWordsBox(VectorFont font)
    {
        var box = new BoxContainer
        {
            Align = BoxContainer.AlignMode.Center,
            Margin = new Thickness(0, 0, 0, 50),
        };

        box.AddChild(new Label
        {
            Text = Loc.GetString("round-end-credits-trauma-lastwords-title"),
            FontOverride = font,
        });

        return box;
    }

    private BoxContainer MakeLastWordsBox(VectorFont font, RoundEndMessageEvent.RoundEndPlayerInfo[] players)
    {
        var box = new BoxContainer
        {
            Align = BoxContainer.AlignMode.Center,
            Orientation = BoxContainer.LayoutOrientation.Vertical,
        };

        foreach (var player in players)
        {
            if (player.LastWords != null)
            {
                box.AddChild(new Label
                {
                    FontOverride = font,
                    Text = Loc.GetString("round-end-credits-trauma-lastwords", ("words", player.LastWords), ("player", player.PlayerICName ?? "Unknown")),
                    Align = Label.AlignMode.Center,
                });
            }
        }

        return box;
    }
}
