// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Lobby;
using Content.Client.UserInterface.Controls;
using Content.Trauma.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Ghost.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostCharacterWindow : FancyWindow
{
    [Dependency] private IClientPreferencesManager _prefs = default!;

    public event Action<int?>? OnSlotSet;
    public RadioOptions<int?> Buttons = new(RadioOptionsLayout.Vertical);

    public GhostCharacterWindow(CharacterData data)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ScrollContainer.AddChild(Buttons);

        AddCharacterButtons(data);
        AddRandomOption();

        Buttons.SelectByValue(data.DesiredSlot);

        Buttons.OnItemSelected += args =>
        {
            Buttons.Select(args.Id);
            OnSlotSet?.Invoke(Buttons.SelectedValue);
        };
    }

    private void AddCharacterButtons(CharacterData data)
    {
        if (_prefs.Preferences is not {} prefs)
            return;

        foreach (var (slot, profile) in prefs.Characters)
        {
            var name = profile.Name;
            var idx = Buttons.AddItem(name, slot);
            // don't allow picking already spawned characters
            Buttons.SetItemDisabled(idx, data.SpawnedNames.Contains(name));
        }
    }

    private void AddRandomOption()
    {
        Buttons.AddItem(Loc.GetString("ghost-character-window-random-character"), null);
    }
}
