- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 10h # Goob - was 5h
  - !type:DepartmentTimeRequirement # Goob
    department: Security
    time: 10h
  - !type:SpeciesRequirement # Goob
    inverted: true
    species:
    - Plasmaman
  guides: [ NuclearOperatives ]
  creditImage: /Textures/_Trauma/EndCredits/Antags/nukeops.png # Trauma

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 25h # Goob - was 5h
  - !type:DepartmentTimeRequirement # Goob
    department: Security
    time: 10h
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 5h # Goob - was 3h
  - !type:SpeciesRequirement # Goob
    inverted: true
    species:
    - Plasmaman
  guides: [ NuclearOperatives ]
  dontShowInCredits: true # Trauma

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 25h # Goob - was 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10h # Goob - was 5h
  - !type:DepartmentTimeRequirement # Goob
    department: Command
    time: 5h
# should be changed to nukie playtime when thats tracked (wyci)
  - !type:SpeciesRequirement # Goob
    inverted: true
    species:
    - Plasmaman
  guides: [ NuclearOperatives ]
  dontShowInCredits: true # Trauma

- type: antagSpecifier
  abstract: true
  parent: RestrictedAntag
  id: BaseNukeops
  prefRoles:
  - GenericTeamAntagonist # For antag ban purposes
  roleLoadout:
  - RoleSurvivalNukie
  components:
  - type: NukeOperative
  - type: NpcFactionMember
    factions:
    - Syndicate

- type: antagSpecifier
  parent: BaseNukeops
  id: NukeopsCommander
  prefRoles:
  - NukeopsCommander
  spawnerPrototype: SpawnPointNukeopsCommander
  startingGear: SyndicateCommanderGearFull
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicateElite
    nameFormat: name-format-nukie-commander
  mindRoles:
  - MindRoleNukeopsCommander

- type: antagSpecifier
  parent: BaseNukeops
  id: NukeopsMedic
  prefRoles:
  - NukeopsMedic
  spawnerPrototype: SpawnPointNukeopsMedic
  startingGear: SyndicateOperativeMedicFull
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicateNormal
    nameFormat: name-format-nukie-agent
  - type: SurgerySpeedModifier # Trauma
    speedModifier: 2
  mindRoles:
  - MindRoleNukeopsMedic

- type: antagSpecifier
  parent: BaseNukeops
  id: NukeopsOperative
  prefRoles:
  - Nukeops
  spawnerPrototype: SpawnPointNukeopsOperative
  startingGear: SyndicateOperativeGearFull
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicateNormal
    nameFormat: name-format-nukie-operator
  mindRoles:
  - MindRoleNukeops

- type: antagSpecifier
  parent: BaseNukeops
  id: LoneOp
  spawnerPrototype: SpawnPointLoneNukeOperative
  pickPlayer: false
  startingGear: SyndicateLoneOperativeGearFull
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicatePrefix
    - NamesSyndicateNormal
    nameFormat: name-format-nukie-generic
  mindRoles:
  - MindRoleLoneops

- type: startingGear
  id: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    #outerClothing: ClothingOuterHardsuitSyndie # goobstation - duke nukies
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiOperativePDA
    pocket2: PlushieCarp
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio225TC # Goobstation - Telecrystal rework

- type: chameleonOutfit
  id: NukeopsOutfit
  name: roles-antag-nuclear-operative-name
  startingGear: SyndicateOperativeGearFullNoUplink
  icon: "JobIconSyndicateOperative"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndie
    neck: ClothingNeckScarfStripedSyndieRed

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    id: SyndiCommanderPDA
    neck: SyndicateWhistle
    pocket2: BaseUplinkRadio350TC # goobstation - im rich :fire::fire:
    #outerClothing: ClothingOuterHardsuitSyndieCommander # goobstation - duke nukies
    ears: ClothingHeadsetAltSyndicateCommander # goob - loudspeaker
  inhand:
  - ToolboxSyndicateFilledWar # Trauma

- type: chameleonOutfit
  id: NukeopsCommanderOutfit
  name: roles-antag-nuclear-operative-commander-name
  startingGear: SyndicateCommanderGearFull
  icon: "JobIconSyndicateCommander"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieCommander
    neck: ClothingNeckScarfStripedSyndieGreen

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    back: ClothingBackpackDuffelSyndicateMedical # Goobstation
    eyes: ClothingEyesHudSyndicate
    #outerClothing: ClothingOuterHardsuitSyndieMedic # goobstation - duke nukies
    shoes: ClothingShoesBootsMagSyndie
    belt: ClothingBeltChemBagSyndiFilled # Goobstation - replace webbing
    pocket2: BaseUplinkRadio225TCMedic # Goob
  storage:
    back:
    - SyndiHypo
    #- SawAdvanced # Shitmed
    #- Cautery # Shitmed
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    #- HandheldHealthAnalyzer # Goobstation
    - CombatMedipen
    - DeathAcidifierImplanter
    - MedkitCombatFilled # Goobstation

- type: chameleonOutfit
  id: NukeopsMedicOutfit
  name: roles-antag-nuclear-operative-agent-name
  startingGear: SyndicateOperativeMedicFull
  icon: "JobIconSyndicateCorpsman"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieMedic
    neck: ClothingNeckScarfStripedLightBlue

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    # Goobstation - Telecrystal rework
    pocket2: LoneOpsUplink225TC #Trauma
