- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  guides: [ Traitors ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
  creditImage: /Textures/_Trauma/EndCredits/Antags/traitor.png # Trauma

- type: antagSpecifier
  abstract: true
  parent: RestrictedAntag
  id: BaseTraitor
  # <Trauma>
  blacklist:
    components:
    - AntagImmune
    - Changeling
  # </Trauma>

- type: antagSpecifier
  parent: BaseTraitor
  id: Traitor
  prefRoles:
  - Traitor
  # Trauma - removed blacklist copy, its inherited
  mindRoles:
  - MindRoleTraitor

- type: antag
  id: TraitorSleeper
  name: roles-antag-syndicate-agent-sleeper-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-sleeper-objective
  guides: [ Traitors ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h

- type: antagSpecifier
  parent: BaseTraitor
  id: TraitorSleeper
  prefRoles:
  - TraitorSleeper
  mindRoles:
  - MindRoleTraitorSleeper

- type: antagSpecifier
  parent: BaseTraitor
  id: TraitorReinforcement
  prefRoles:
  - Traitor
  - GenericTeamAntagonist # Matters for Antag bans.
  mindRoles:
  - MindRoleTraitorReinforcement

# Syndicate Operative Outfit - Monkey
- type: startingGear
  id: SyndicateOperativeGearMonkey
  equipment:
    head: ClothingHeadHatOutlawHat
    jumpsuit: ClothingUniformJumpsuitOperative
    mask: CigaretteSyndicate

# Syndicate Operative Outfit - Barratry
- type: startingGear
  id: SyndicateOperativeGearExtremelyBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

- type: startingGear
  id: SyndicateOperativeClothing
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsSyndieFilled
    # <Trauma>
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicate
    # </Trauma>
    gloves: ClothingHandsGlovesColorBlack

- type: startingGear
  parent: SyndicateOperativeClothing # Trauma
  id: SyndicateReinforcementMedic
  equipment:
    # <Trauma>
    eyes: ClothingEyesHudSyndicateAgent
    id: SyndiMedicPDA
    gloves: ClothingHandsGlovesNitrile
    pocket1: WeaponPistolViper
  inhand:
    - ClothingBackpackDuffelSyndicateFilledMedical
  storage:
    back:
    - MedkitCombatFilled
    - CigPackSyndicate # 1
    - CigPackSyndicate # 2
    - InterdyneFlippo
    - CombatMedipen # 1
    # </Trauma>

- type: startingGear
  parent: SyndicateOperativeClothing # Trauma
  id: SyndicateReinforcementSpy
  equipment:
    # <Trauma>
    gloves: ClothingHandsGlovesColorBlack
    pocket1: WeaponPistolCobra
  inhand:
    - ClothingBackpackChameleonFillAgent
  storage:
    back:
    - VoiceMaskImplanter
    - MagazinePistolCaselessRifle # 1
    - MagazinePistolCaselessRifle # 2
    - RadioJammer
    - ChameleonProjector
    # </Trauma>

- type: startingGear
  id: SyndicateReinforcementThief
  # <Trauma>
  parent: SyndicateOperativeClothing
  equipment:
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsChameleonThief
    pocket1: WeaponPistolViper
  storage:
    back:
    - MagazinePistolHighCapacity # 1
    - MagazinePistolHighCapacity # 2
    - SyndicateJawsOfLife
    - CameraBug
    - Fulton
    - FultonBeacon
  # </Trauma>

#Syndicate Operative Outfit - Basic
- type: startingGear
  id: SyndicateOperativeGearBasic
  parent: SyndicateOperativeGearExtremelyBasic
  equipment:
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    pocket1: BaseUplinkRadio200TC # Goobstation - Telecrystal rework
    id: SyndiPDA
