# SPDX-License-Identifier: AGPL-3.0-or-later

# All actions in here are the base actions of the vampire that hasn't specialized yet.
# Therefore, this file does not include class-specific actions.
# Abstract Actions
- type: entity
  parent: BaseAction
  id: BaseVampireAction
  components:
  - type: Action
    raiseOnAction: true
    itemIconStyle: BigAction
  - type: ActionConditions
    failPopup: The holiness has consumed your powers!
    conditions:
    - !type:HasNullificationCondition # cannot use abilities if we are too nullified
      inverted: true
      amount: 100
    - !type:InsideAreaCondition # cannot use abilities if we are in chapel
      inverted: true
      whitelist:
        components:
        - HolyArea

- type: entity
  parent: BaseVampireAction
  id: BaseRejuvAction
  components:
  - type: Action
    useDelay: 20
    sound:
      path: /Audio/_Trauma/Vampires/Actions/vampire_rejuv.ogg
    icon:
      sprite: _Trauma/Vampires/actions.rsi
      state: vampire_rejuvinate
    checkCanInteract: false
  - type: InstantAction
    event: !type:EffectInstantActionEvent

# Rejuv
- type: entity
  parent: BaseRejuvAction
  id: ActionVampRejuvenateI
  name: Rejuvenate I
  description: Removes any and all stuns. Removes 100 stamina damage.
  components:
  - type: EffectAction
    effects:
    - !type:NestedEffect
      proto: VampireRejuvI

- type: entity
  parent: BaseRejuvAction
  id: ActionVampRejuvenateII
  name: Rejuvenate II
  description: Removes any and all stuns. Purges 10u of any harmful reagent. Heals 10 points each of brute, burn, toxin, and heals 50 points of oxyloss.
  components:
  - type: EffectAction
    effects:
    - !type:NestedEffect
      proto: VampireRejuvII

# Glare
- type: entity
  parent: BaseVampireAction
  id: ActionVampireGlare
  name: Glare
  description: Works in melee-range, and has different effects on each side of you. Requires 2 charges to fully stun.
  components:
  - type: Action
    useDelay: 2
    sound:
      path: /Audio/_Trauma/Vampires/Actions/vampire_glare.ogg
    icon:
      sprite: _Trauma/Vampires/actions.rsi
      state: vampire_glare
  - type: LimitedCharges
    maxCharges: 2
  - type: AutoRecharge
    rechargeDuration: 30
  - type: EffectAction
    onPerformed: true
    effects:
    - !type:SpawnParticles
      particleProto: VampireGlare
  - type: InstantAction
    event: !type:VampireGlareEvent
  - type: ActionVampireGlare
    frontEffects:
    - !type:TakeStaminaDamage
      amount: 100
    - !type:ModifyKnockdown
      time: 12
    - !type:GenericStatusEffect
      key: Muted
      component: Muted
      time: 16
      type: Add
    - !type:Flash
      slowTo: 1
      maxRange: 0.5
      duration: 1
    sideEffects:
    - !type:TakeStaminaDamage
      amount: 50
    - !type:ModifyKnockdown
      time: 5
    - !type:ModifyStatusEffect
      effectProto: StatusEffectScrambled
      time: 8
    behindEffects:
    - !type:TakeStaminaDamage
      amount: 50
    - !type:ModifyStatusEffect
      effectProto: StatusEffectScrambled
      time: 8

- type: entity
  parent: BaseVampireAction
  id: ActionChooseSpecialization
  name: Choose Specialization
  description: Choose Specialization
  components:
  - type: Action
    icon:
      sprite: _Trauma/Vampires/actions.rsi
      state: select_class
  - type: InstantAction
    event: !type:OpenClassSelectorUiEvent
  - type: UserInterface
    interfaces:
      enum.MobClassUiKey.Key:
        type: MobClassSelectorBui
  - type: ActionMobClass

# Lair
- type: entity
  parent: BaseVampireAction
  id: ActionCreateLair
  name: Create Lair
  description: Use the action on a coffin to make it your lair. You will heal inside the lair, and be able to teleport to it on death. You can only make one lair, so be careful.
  components:
  - type: Action
    icon:
      sprite: _Trauma/Vampires/actions.rsi
      state: lair
  - type: TargetAction
    range: 2
  - type: EntityTargetAction
    event: !type:ActionLairEvent
  - type: ActionLair

- type: entity
  parent: BaseVampireAction
  id: ActionTeleportLair
  name: Teleport To Lair
  description: Use this action when you are dead or crit, in order to teleport to your lair.
  components:
  - type: Action
    checkCanInteract: false
    checkConsciousness: false
    useDelay: 500
    icon:
      sprite: _Trauma/Vampires/actions.rsi
      state: lair_tp
  - type: InstantAction
    event: !type:ActionLairTeleportEvent
  - type: ActionLairTeleport
