- type: entity
  parent: AccessConfigurator
  id: AccessConfiguratorSyndicate
  name: syndicate access configurator
  description: A Cybersun branded access configurator, compatible with both NanoTrasen and Syndicate IDs. Now with quick swap functionality!
  components:
  - type: Sprite
    sprite: _Trauma/Objects/Tools/syndie_access_configurator.rsi
  - type: Clothing
    sprite: _Trauma/Objects/Tools/syndie_access_configurator.rsi
  - type: AccessOverrider
    accessLevels:
    - SyndicateAgent
    - NuclearOperative
