# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  abstract: true
  id: BaseBodyPartCavity
  components:
  - type: BodyPartCavity
    whitelist: # any tiny or small item, thats it
      sizes:
      - Tiny
      - Small
