# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Blob
  name: roles-antag-blob-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blob-objective
  guides: [ Blob ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 5h
  creditImage: /Textures/_Trauma/EndCredits/Antags/blob.png

- type: antagSpecifier
  parent: CommandBlacklistedAntag
  id: Blob
  prefRoles: [ Blob ]
  allowNonHumans: true
  briefing:
    text: blob-carrier-role-greeting
    color: Plum
    sound: /Audio/Announcements/bloblarm.ogg
  mindRoles:
  - MindRoleBlob
