# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antagSpecifier
  abstract: true
  id: BaseHonkops
  roleLoadout: [ RoleSurvivalNukieHonkops ]
  components:
  # clown
  - type: Clumsy
  - type: SleepEmitSound
    snore: /Audio/Voice/Misc/silly_snore.ogg
    interval: 10
  - type: SpeechFontOverride
    font: LDFComicSans
  - type: RandomMetadata
    nameSegments:
    - NamesHonkopsPrefix
    - NamesHonkopsElite # all clowns are created equal
    nameFormat: name-format-standard

- type: antagSpecifier
  parent: [ NukeopsCommander, BaseHonkops ]
  id: HonkopsCommander
  startingGear: SyndicateCommanderGearFullHonkops

- type: antagSpecifier
  parent: [ NukeopsMedic, BaseHonkops ]
  id: HonkopsMedic
  startingGear: SyndicateOperativeMedicFullHonkops

- type: antagSpecifier
  parent: [ NukeopsOperative, BaseHonkops ]
  id: HonkopsOperative
  startingGear: SyndicateOperativeGearFullHonkops

- type: startingGear
  id: SyndicateOperativeGearFullNoUplinkHonkops
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskClownUnremoveable
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesClownLarge
    id: SyndiPDA
    pocket1: BikeHorn
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFullHonkops
  parent: SyndicateOperativeGearFullNoUplinkHonkops
  equipment:
    pocket2: BaseUplinkRadio225TC

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFullHonkops
  parent: SyndicateOperativeGearFullNoUplinkHonkops
  equipment:
    neck: SyndicateWhistle
    pocket2: BaseUplinkRadio350TC
  inhand:
  - NukeOpsDeclarationOfWar

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFullHonkops
  parent: SyndicateOperativeGearFullNoUplinkHonkops
  equipment:
    back: ClothingBackpackDuffelSyndicateMedical
    eyes: ClothingEyesHudSyndicateAgent
    id: SyndiCorpsmanPDA
    belt: ClothingBeltChemBagSyndiFilled
    pocket2: BaseUplinkRadio225TCMedic
  storage:
    back:
    - SyndiHypo
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - CombatMedipen
    - DeathAcidifierImplanter
    - MedkitCombatFilled
