- type: startingGear
  id: GreyTideAntagGear
  equipment:
    mask: ClothingMaskGasUnremoveable
    jumpsuit: ClothingUniformJumpsuitAncientUnremoveable
    shoes: ClothingShoesColorBlackUnremoveable
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    belt: ClothingBeltUtilityFilledUnremoveable
    gloves: ClothingHandsGlovesColorYellowUnremovable
    back: ClothingBackpackUnremoveable
  inhand:
  - Toolboxrobust

- type: startingGear
  id: TunnelClownAntagGear
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskClownUnremoveable
    jumpsuit: ClothingUniformJumpsuitClown
    outerClothing: ClothingOuterCoatJacketBiker
    shoes: ClothingShoesClownUnremoveable
    id: ClownPDA
    pocket1: BikeHorn
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackClown
  inhand:
  - FireAxe
  - Stunbaton
  storage:
    back:
    - ClownRecorder
    - FoodMeatClown
    - TunnelClownBusinessCard
    - Handcuffs
    - Handcuffs
    - VialCocaine
    - VialGreen
    - MedkitCombatFilled
    - SprayPaintFunny
    - SprayPaintFunnyYellow
    - TrashBananaPeelExplosive
    - TrashBananaPeelExplosive

- type: startingGear
  id: SingulothKnightsAntagGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    outerClothing: ClothingSingulothArmor
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltUtilityEngineering
    pocket1: ScrollTeleportApprentice # intended to teleport to engineering/tesla
  inhand:
  - SingulothsHammer
  storage:
    back:
    - MedkitCombatFilled
    - OxygenTankFilled
    - Bible

- type: startingGear
  id: DarkLordAntagGear
  equipment:
    head: ClothingHeadHatHoodCloakSith
    jumpsuit: ClothingUniformJumpsuitMonasticRobeDark
    outerClothing: ClothingOuterWizardBlackReal
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackSatchelLeather
    id: SyndiPDA
  inhand:
  - EnergySwordDoubleRed
  storage:
    back:
    - BoxSurvivalSlotsSyndicate
    - MedkitCombatFilled

- type: startingGear
  id: ChosenOneProtagGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    outerClothing: WhiteRobes
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltAssaultFilled
    id: CentcomPDA
  inhand:
  - EnergySwordBlue

- type: startingGear
  id: MimeAssassinGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    eyes: ClothingEyesGlassesHiddenSecurity
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterArmourInvisibleSyndie
    id: MimePDA
    pocket1: SyringePistol
    pocket2: KukriKnife
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitMime
    mask: ClothingMaskMime
    head: ClothingHeadHatBeretFrench
    back: ClothingBackpackMime
  storage:
    back:
    - RubberStampMime
    - AdvMimeryVol1
    - AdvMimeryVol2
    - CrayonMime
    - SyndicateBusinessCard
    - ChameleonProjector
    - ChemistryBottleNocturine
    - ChemistryBottleNocturine
    - Syringe
    - Syringe
    - DeathAcidifierImplanter
    - FreedomImplanter
    - SmokeImplanter
    - BodyBagFolded

- type: startingGear
  id: DarkPriestAntagGear
  equipment:
    head: ClothingHeadHatHoodVoidCloak
    eyes: ClothingEyesGlassesHiddenSecurity
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitChaplain
    shoes: ClothingShoesColorBlack
    neck: ClothingNeckStoleChaplain
    id: ChaplainPDA
    outerClothing: ClothingOuterHoodieChaplain
    back: ClothingBackpack
  inhand:
  - BlessingOfTheReaper
  storage:
    back:
    - Bible
    - ArmamentsBeacon
    - ClothingNeckStoleChaplain
    - ClothingHeadHatHoodVoidCloak
    - ClothingOuterHoodieChaplain
    - BoxSurvivalSlots

- type: startingGear
  id: VoxRaiderAntagGear
  equipment:
    ears: ClothingHeadsetAltSyndicate
    jumpsuit: ClothingUniformJumpsuitTacticool
    shoes: ClothingShoesColorBlack
    id: SyndiPDA
    mask: ClothingMaskGasSyndicate
    gloves: ClothingHandsChameleonThief
    outerClothing: ClothingOuterHardsuitVoxRaiderStealth
    suitstorage: ExtendedEmergencyNitrogenTankFilled
    back: ClothingBackpackSyndicate
  storage:
    back:
    - BoxSurvivalSlotsNitrogen
    - ExtendedEmergencyNitrogenTankFilled
    - ChameleonProjector
    - DartGun
    - ChemistryBottleNocturine
    - ChemistryBottleNocturine
    - AgentIDCard
    - ThiefBeacon
