- type: startingGear
  id: GreyTideAntagGear
  equipment:
    mask: ClothingMaskGasUnremoveable
    jumpsuit: ClothingUniformJumpsuitAncientUnremoveable
    shoes: ClothingShoesColorBlackUnremoveable
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    belt: ClothingBeltUtilityFilledUnremoveable
    gloves: ClothingHandsGlovesColorYellowUnremovable
    back: ClothingBackpackUnremoveable
  inhand:
  - Toolboxrobust

- type: antagSpecifier
  id: TunnelClown
  spawnerPrototype: SpawnPointGhostTunnelClown
  mindRoles:
  - MindRoleGhostRoleSoloAntagonist
  briefing:
    text: tunnel-clown-role-greeting
    color: Pink
    sound: /Audio/_Goobstation/Misc/clownalwayswinsshort.ogg

- type: startingGear
  id: TunnelClownAntagGear
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskClownUnremoveable
    jumpsuit: ClothingUniformJumpsuitClown
    outerClothing: ClothingOuterCoatJacketBiker
    shoes: ClothingShoesClownUnremoveable
    id: ClownPDA
    pocket1: BikeHorn
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackClown
  inhand:
  - FireAxe
  - Stunbaton
  storage:
    back:
    - ClownRecorder
    - FoodMeatClown
    - TunnelClownBusinessCard
    - Handcuffs
    - Handcuffs
    - VialCocaine
    - VialGreen
    - MedkitCombatFilled
    - SprayPaintFunny
    - SprayPaintFunnyYellow
    - TrashBananaPeelExplosive
    - TrashBananaPeelExplosive

- type: antagSpecifier
  id: SingulothKnight
  spawnerPrototype: SpawnPointGhostSingulothKnight
  mindRoles: [ MindRoleGhostRoleFreeAgent ]
  briefing:
    text: Singuloth-Knight-role-greeting
    color: Red
    sound: /Audio/_Goobstation/Misc/singulothknight_greeting.ogg

- type: startingGear
  id: SingulothKnightsAntagGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    outerClothing: ClothingSingulothArmor
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltUtilityEngineering
    pocket1: ScrollTeleportApprentice # intended to teleport to engineering/tesla
  inhand:
  - SingulothsHammer
  storage:
    back:
    - MedkitCombatFilled
    - OxygenTankFilled
    - Bible

- type: antagSpecifier
  id: DarkLord
  spawnerPrototype: SpawnPointGhostDarkLord
  mindRoles: [ MindRoleGhostRoleSoloAntagonist ]
  briefing:
    text: dark-lord-role-greeting
    color: Red
    sound: /Audio/_Goobstation/Misc/darklord_greeting.ogg

- type: startingGear
  id: DarkLordAntagGear
  equipment:
    head: ClothingHeadHatHoodCloakSith
    jumpsuit: ClothingUniformJumpsuitMonasticRobeDark
    outerClothing: ClothingOuterWizardBlackReal
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackSatchelLeather
    id: SyndiPDA
  inhand:
  - EnergySwordDoubleRed
  storage:
    back:
    - BoxSurvivalSlotsSyndicate
    - MedkitCombatFilled

- type: antagSpecifier
  id: ChosenOne
  spawnerPrototype: SpawnPointGhostChosenOne
  mindRoles: [ MindRoleGhostRoleNeutral ]
  briefing:
    text: chosen-one-role-greeting
    color: Green
    sound: /Audio/_Goobstation/Misc/darklord_greeting.ogg

- type: startingGear
  id: ChosenOneProtagGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    outerClothing: WhiteRobes
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltAssaultFilled
    id: CentcomPDA
  inhand:
  - EnergySwordBlue

- type: antagSpecifier
  id: MimeAssassin
  spawnerPrototype: SpawnPointGhostMimeAssassin
  mindRoles:
  - MindRoleGhostRoleSoloAntagonist
  briefing:
    text: mime-Assassin-role-greeting
    color: Red
    sound: /Audio/Misc/thief_greeting.ogg

- type: startingGear
  id: MimeAssassinGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    eyes: ClothingEyesGlassesHiddenSecurity
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterArmourInvisibleSyndie
    id: MimePDA
    pocket1: SyringePistol
    pocket2: KukriKnife
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitMime
    mask: ClothingMaskMime
    head: ClothingHeadHatBeretFrench
    back: ClothingBackpackMime
  storage:
    back:
    - RubberStampMime
    - AdvMimeryVol1
    - AdvMimeryVol2
    - CrayonMime
    - SyndicateBusinessCard
    - ChameleonProjector
    - ChemistryBottleNocturine
    - ChemistryBottleNocturine
    - Syringe
    - Syringe
    - DeathAcidifierImplanter
    - FreedomImplanter
    - SmokeImplanter
    - BodyBagFolded

- type: antagSpecifier
  id: DarkPriest
  spawnerPrototype: SpawnPointGhostDarkPriest
  mindRoles: [ MindRoleGhostRoleFreeAgent ]
  briefing:
    text: dark-priest-role-greeting
    color: Purple
    sound: /Audio/_Goobstation/Heretic/Ambience/Antag/Heretic/heretic_gain.ogg

- type: startingGear
  id: DarkPriestAntagGear
  equipment:
    head: ClothingHeadHatHoodVoidCloak
    eyes: ClothingEyesGlassesHiddenSecurity
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitChaplain
    shoes: ClothingShoesColorBlack
    neck: ClothingNeckStoleChaplain
    id: ChaplainPDA
    outerClothing: ClothingOuterHoodieChaplain
    back: ClothingBackpack
  inhand:
  - BlessingOfTheReaper
  storage:
    back:
    - Bible
    - ArmamentsBeacon
    - ClothingNeckStoleChaplain
    - ClothingHeadHatHoodVoidCloak
    - ClothingOuterHoodieChaplain
    - BoxSurvivalSlots

- type: antagSpecifier
  id: VoxRaider
  spawnerPrototype: SpawnPointGhostVoxRaider
  mindRoles:
  - MindRoleGhostRoleTeamAntagonist
  - MindRoleThief
  briefing:
    text: vox-raider-role-greeting
    color: Purple
    sound: /Audio/Misc/thief_greeting.ogg

- type: startingGear
  id: VoxRaiderAntagGear
  equipment:
    ears: ClothingHeadsetAltSyndicate
    jumpsuit: ClothingUniformJumpsuitTacticool
    shoes: ClothingShoesColorBlack
    id: SyndiPDA
    mask: ClothingMaskGasSyndicate
    gloves: ClothingHandsChameleonThief
    outerClothing: ClothingOuterHardsuitVoxRaiderStealth
    suitstorage: ExtendedEmergencyNitrogenTankFilled
    back: ClothingBackpackSyndicate
  storage:
    back:
    - BoxSurvivalSlotsNitrogen
    - ExtendedEmergencyNitrogenTankFilled
    - ChameleonProjector
    - DartGun
    - ChemistryBottleNocturine
    - ChemistryBottleNocturine
    - AgentIDCard
    - ThiefBeacon
